version: '3'

services:
  app:
    image: marcusaloise/giropops-senhas:2.0
    ports:
      - "5000:5000"
    networks: 
      - strigus
    environment:
      REDIS_HOST: redis
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - strigus
      
networks:
  strigus:
    driver: bridge 
