version: '3'
services:
  app:
    build: ./Dockerfile-app
    ports:
      - "5000:5000"
    networks:
      - strigus
    environment:
      REDIS_HOST: redis
    volumes:
      - girus:/girus
    deploy:
      replicas: 1
      resources:
        reservations:
          cpus: '0.25'
          memory: 128M
        limits:
          cpus: '0.5'
          memory: 256M
    depends_on:
      - redis

  redis:
    image: redis
    command: redis-server --appendonly yes
    networks:
      - strigus
    volumes:
      - girus:/girus
    deploy:
      replicas: 1
      resources:
        reservations:
          cpus: '0.25'
          memory: 128M
        limits:
          cpus: '0.5'
          memory: 256M
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  strigus:
    driver: bridge
volumes:
  girus:
